version: '3.5'
services:
  nestapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baguette-store
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/baguette-store
      - ./node_modules:/usr/src/baguette-store/node_modules

networks:
  default:
    external: true
    name: test-network